#!/bin/bash

# A script to download subtitles of a youtube playlist / video.

# Credits:
# 	- Author: https://gist.github.com/aswathm78
#	- Gist Link: https://gist.github.com/aswathm78/1f25ef7583d4498d6df28914d15e968a

yt-dlp --write-auto-sub --sub-lang en --skip-download -o '%(title)s.%(ext)s' $1 

