#!/usr/bin/env python

import sys
import os

repourl = sys.argv[1] #https://github.com/mwaseemrandhawa/Urdu-News-Headline-Dataset
l_slash = repourl.rfind('/') # last forward slash index
reponame = repourl[l_slash+1:]
sl_slash = repourl.rfind('/', 0, l_slash) # second last forward slash index
username = repourl[sl_slash+1: l_slash]

clonedir = os.path.join(os.getcwd(), f'{reponame}_{username}')

cmd = f'git clone {repourl} {clonedir}'
print('Running:', cmd)
os.system(cmd)

