#!/data/data/com.termux/files/usr/bin/sh
termux-wake-lock
termux-wifi-enable true
sleep 30

rclone -v --progress sync /data/data/com.termux/files/home/storage/shared/kxc/ t220:kxc

rclone -v --progress sync /data/data/com.termux/files/home/storage/shared/Backups talmeez:/backup/Backups

rclone -v --progress sync /data/data/com.termux/files/home/storage/shared/Documents talmeez:/backup/Documents

rclone -v --progress sync /data/data/com.termux/files/home/storage/shared/DCIM gallery:a30

termux-notification -c "daily backup complete"
termux-wake-unlock
exit
