#!/data/data/com.termux/files/usr/bin/sh

termux-wake-lock
termux-wifi-enable true
sleep 30

echo "syncing kxc..."
rclone -v --progress sync /data/data/com.termux/files/home/storage/shared/kxc/ t220:kxc


for path in /data/data/com.termux/files/home/storage/shared/*
do
    dir="$(basename -- $path)"
    if [ "$dir" = "AudioRecorder" ] || [ "$dir" = "Backups" ] || [ "$dir" = "Documents" ] || [ "$dir" = "Download" ] || [ "$dir" = "Pictures" ] || [ "$dir" = "QKSMS" ] || [ "$dir" = "Ringtones" ] || [ "$dir" = "Notifications" ]
    then
        echo "syncing $dir"
        rclone --progress sync $path android:/$dir
    fi
done

echo "syncing whatsapp..."
rclone -v --progress sync /data/data/com.termux/files/home/storage/shared/Android/media/com.whatsapp/ android:/whatsapp

echo "copying gallery..."
# dont sync bcz it will delete files in cloud. just copy current ones
rclone -v --progress copy /data/data/com.termux/files/home/storage/shared/DCIM gallery:a30

#enable cron daemon
#sv-enable crond 

termux-notification -c "daily backup complete"
termux-wifi-enable false
termux-wake-unlock
exit
