#!/usr/bin/bash
# https://wiki.archlinux.org/title/KDE#Disable_panel_shadow
sleep 45
for WID in $(xwininfo -root -tree | sed '/"Plasma": ("plasmashell" "plasmashell")/!d; s/^  *\([^ ]*\) .*/\1/g'); do
   xprop -id $WID -remove _KDE_NET_WM_SHADOW
done
