#!/bin/bash

# A script to download subtitles of a youtube playlist / video.

# Credits:
# 	- Author: https://gist.github.com/aswathm78
#	- Gist Link: https://gist.github.com/aswathm78/1f25ef7583d4498d6df28914d15e968a
mkdir -vp storage/shared/Movies/ytdlp
cd ~/storage/shared/Movies/ytdlp
#rm -v *
yt-dlp -o "%(playlist_index)s-%(title)s.%(ext)s" -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' $@
termux-notification -c "Download complete"
